CC = gcc

CFLAGS_RET2WIN    = -fno-stack-protector -no-pie -z execstack -z norelro
CFLAGS_RET2LIBC   = -fno-stack-protector -no-pie -z relro
CFLAGS_SHELLCODE  = -fno-stack-protector -no-pie -z execstack -z norelro
CFLAGS_FMTREAD    = -fno-stack-protector -no-pie -z norelro -Wno-format-security
CFLAGS_FMTWRITE   = -fno-stack-protector -no-pie -z norelro -Wno-format-security

BINARIES = ret2win_x64 ret2libc_x64 shellcode_x64 format_read_x64 format_write_x64

all: $(BINARIES)

ret2win_x64: ret2win.c
	$(CC) $(CFLAGS_RET2WIN) -o $@ $<

ret2libc_x64: ret2libc.c
	$(CC) $(CFLAGS_RET2LIBC) -o $@ $<

shellcode_x64: shellcode.c
	$(CC) $(CFLAGS_SHELLCODE) -o $@ $<

format_read_x64: format_read.c
	$(CC) $(CFLAGS_FMTREAD) -o $@ $<

format_write_x64: format_write.c
	$(CC) $(CFLAGS_FMTWRITE) -o $@ $<

clean:
	rm -f $(BINARIES)

.PHONY: all clean
